name: KeepEnchant
version: '${project.version}'
main: de.tamion.KeepEnchant
load: STARTUP
authors: [Tamion]
description: Allows you to keep the enchantment when using the grindstone

commands:
  keepenchant: